### PR TITLE
solve link error / named enums / 1.11.1 bindings

### PR DESCRIPTION
**Pull request by rtbo**
Hello Vild

I propose this pull request to enhance xcb-d.
The latest commit is most necessary as it solves linker error when using extension (__gshared missing: the linker cannot link global var to thread local storage)

The commit with named enums is more invasive. it allows to use typesafe enums and add global aliases to each member. client code is normally not broken. (at least mine isn't). I can just remove this commit if you dislike it.

If you accept the pull request, please also tag it (as I did in my fork) so that we can refer to it with dub.

Thanks and regards,
Rémi

### CODE REVIEW

**Comment by Vild** [comment]
I see now that I missed __gshared, good work catching that. :+1:

The enum change seems like a good idea.
I think I might try and change so functions use the enum type instead of a integer type.
This should complement your commit and make the ABI more secure.

Before I tag v1.1.1 I will make sure that d_client.py represents the latest c_client.py

**Comment by Vild** [comment]
Changes are pushed into master.

**Comment by Vild** [comment]
My change to try and make the functions take enum types instead of integer types did not work out.

You commits are now tagged and the package is updated on code.dlang.org.

**Comment by rtbo** [comment]
Hello Dan

Thanks for this

I also tried to see if the xcb api could accept enum types, but as a fact, the C api itself only uses regular integral types.

I still like to be able to use the safe enums in client code

Rémi

**Comment by Vild** [comment]
It would have worked because a enum is always a number in the backend and every integer type less than a int is promoted a int.
The biggest problem is that the xml format does not always provide what enum is uses. If I remember right.

**Pull request closed without merging**
